/**
 * generated by Xtext 2.23.0
 */
package hu.bme.mit.gamma.theta.trace.language.validation;

import hu.bme.mit.gamma.theta.trace.language.validation.AbstractTraceLanguageValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class TraceLanguageValidator extends AbstractTraceLanguageValidator {
}
