/*
 * generated by Xtext 2.23.0
 */
package hu.bme.mit.gamma.theta.trace.language.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class TraceLanguageUiModule extends AbstractTraceLanguageUiModule {
}
