/*
 * generated by Xtext 2.23.0
 */
package hu.bme.mit.gamma.theta.trace.language


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class TraceLanguageStandaloneSetup extends TraceLanguageStandaloneSetupGenerated {

	def static void doSetup() {
		new TraceLanguageStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
