/*
 * generated by Xtext 2.23.0
 */
package hu.bme.mit.gamma.theta.trace.language


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class TraceLanguageRuntimeModule extends AbstractTraceLanguageRuntimeModule {
}
