/**
 * generated by Xtext 2.23.0
 */
package hu.bme.mit.gamma.theta.trace.language.ui.labeling;

import com.google.inject.Inject;
import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;

/**
 * Provides labels for EObjects.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#label-provider
 */
@SuppressWarnings("all")
public class TraceLanguageLabelProvider extends DefaultEObjectLabelProvider {
  @Inject
  public TraceLanguageLabelProvider(final AdapterFactoryLabelProvider delegate) {
    super(delegate);
  }
}
