/**
 * generated by Xtext 2.23.0
 */
package hu.bme.mit.gamma.theta.trace.language.ui;

import hu.bme.mit.gamma.theta.trace.language.ui.AbstractTraceLanguageUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class TraceLanguageUiModule extends AbstractTraceLanguageUiModule {
  public TraceLanguageUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
