/*
 * generated by Xtext 2.23.0
 */
package hu.bme.mit.gamma.theta.trace.language.ide


/**
 * Use this class to register ide components.
 */
class TraceLanguageIdeModule extends AbstractTraceLanguageIdeModule {
}
