/**
 * generated by Xtext 2.23.0
 */
package hu.bme.mit.gamma.theta.trace.language.ide;

import hu.bme.mit.gamma.theta.trace.language.ide.AbstractTraceLanguageIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class TraceLanguageIdeModule extends AbstractTraceLanguageIdeModule {
}
