/**
 * generated by Xtext 2.23.0
 */
package hu.bme.mit.gamma.theta.trace.language.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import hu.bme.mit.gamma.theta.trace.language.TraceLanguageRuntimeModule;
import hu.bme.mit.gamma.theta.trace.language.TraceLanguageStandaloneSetup;
import hu.bme.mit.gamma.theta.trace.language.ide.TraceLanguageIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class TraceLanguageIdeSetup extends TraceLanguageStandaloneSetup {
  @Override
  public Injector createInjector() {
    TraceLanguageRuntimeModule _traceLanguageRuntimeModule = new TraceLanguageRuntimeModule();
    TraceLanguageIdeModule _traceLanguageIdeModule = new TraceLanguageIdeModule();
    return Guice.createInjector(Modules2.mixin(_traceLanguageRuntimeModule, _traceLanguageIdeModule));
  }
}
