/**
 * generated by Xtext 2.23.0
 */
package hu.bme.mit.gamma.theta.trace.language.ui.contentassist;

import hu.bme.mit.gamma.theta.trace.language.ui.contentassist.AbstractTraceLanguageProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class TraceLanguageProposalProvider extends AbstractTraceLanguageProposalProvider {
}
