/**
 * generated by Xtext 2.23.0
 */
package hu.bme.mit.gamma.theta.trace.language;

import hu.bme.mit.gamma.theta.trace.language.TraceLanguageStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class TraceLanguageStandaloneSetup extends TraceLanguageStandaloneSetupGenerated {
  public static void doSetup() {
    new TraceLanguageStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
