/**
 * generated by Xtext 2.23.0
 */
package hu.bme.mit.gamma.theta.trace.language;

import hu.bme.mit.gamma.theta.trace.language.AbstractTraceLanguageRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class TraceLanguageRuntimeModule extends AbstractTraceLanguageRuntimeModule {
}
